<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>rccontrol</AssemblyName>
    <RootNamespace>Rc.Controller</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rc.Protocol\Rc.Protocol.csproj" />
  </ItemGroup>

</Project>
